services:
  - type: web
    name: screenshot-api
    runtime: node
    buildCommand: npm install
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: 6379
      - key: API_KEY
        value: skimai_key
      - key: DATABASE_URL
        value: file:./dev.db
